### ISSUE TITLE
Passwortverifikation in der Vereinsanmeldung genauer beschreiben

### ISSUE THREAD

**Issue by Tudlluu** [luechtdiode/KuTu#153]
Aktuell ist bei der Vereinsanmeldung bei der Passwortbestätigung lediglich "Verification" im Feld eingetragen.
Um keine Missverständnisse zu generieren, wäre es evtl. sinnvoll "Passwort bestätigen" als Bezeichnung einzufügen.

![image](https://user-images.githubusercontent.com/85314909/120705123-b8989a00-c4b7-11eb-9707-5b1beae51911.png)

**Comment by luechtdiode** [comment]
Passwort-Bestätigen wird angezeigt, wenn noch nichts eingegeben wurde.
