### ISSUE TITLE
Turn10 mit A- und B-Noten anstatt D/E

### ISSUE THREAD

**Issue by luechtdiode** [luechtdiode/KuTu#726]
Im Turn10 Modus sollte die bei Notenanzeigen die D-Note als A-Note angezeigt werden, sowie die E-Note als B-Note.

**Comment by david171290** [comment]
in der mobilen App konnte ich leider noch nicht testen, aber am PC funktioniert das wunderbar.
Sowohl bei der Noteneingabe als auch auf der Rangliste ist die Anzeige korrekt.
Danke

**Comment by david171290** [comment]
habe das Ganze jetzt auch in der Mobile App ausprobiert.
Sieht alles gut aus

Vielen Dank :-)
