### ISSUE TITLE
Gerätewechsel-Reihenfolge bei Barren/Balken (Turn10)

### ISSUE THREAD

**Issue by david171290** [luechtdiode/KuTu#735]
Gibt es gemischte Durchgänge, so gibt es in einem Durchgang das Gerät Barren und das Gerät Balken.

Im Turn10 ist es üblich, dass Barren/Balken parallel geturnt werden.
Barren/Balken wir also in der Gerätewechselfolge als 1 Gerät betrachtet.
-> männliche und weibliche Teilnehmer in der Riege teilen sich auf das entsprechende Gerät auf

In der Software werden die Geräte aktuell gesondert betrachtet, wodurch die Wechselreihenfolge nicht mehr mit der tatsächlichen Reihenfolge zusammen passt.
Dadurch stimmt die Riegenreihenfolge bei den WertungsrichterInnen in der App nicht mehr und auch die Riegenzettel sind in falscher Reihenfolge.

**Comment by luechtdiode** [comment]
Das Programm kann keine Geräte **innerhalb eines Durchgangs** zusammenfassen. Es ist jedoch möglich, die Geräte Barren und Balken als nächstes Gerät nach Boden zu organisieren, sofern die Geräteriegen in einem Durchgang ausschliesslich aus Turner oder Turnerinnen bestehen. Dann können die beiden Durchgänge zu einer Durchgangsgruppe zusammengefasst werden.

**Beispiel**

1. Schritt: Einteilung mit folgender Einstellung
![grafik](https://github.com/luechtdiode/KuTu/assets/2457748/c02e298a-5ff3-4945-b8c7-7307881564ad)
2. Schritt: Durchgänge zusammenfassen
![grafik](https://github.com/luechtdiode/KuTu/assets/2457748/599fc2b3-e5db-4f83-b979-99c6ea014ad0)

Anschliessend werden die Riegenblätter für die Erfassung der Wertungen mit folgender Reihenfolge erstellt:
![grafik](https://github.com/luechtdiode/KuTu/assets/2457748/287a7129-e0b4-462c-821b-cf091b2a8fc4)

Die erstellten Riegenblätter betrachten dann, egal des Geschlechts, den Barren resp den Balken als zweites Gerät:
[KuTuApp PrintingTurn10BarrenBalkenZweitesGeraet.pdf](https://github.com/luechtdiode/KuTu/files/13326359/KuTuApp.PrintingTurn10BarrenBalkenZweitesGeraet.pdf)

[david171290](https://github.com/david171290) Würde das Eure Bedürfnisse abdecken?

**Comment by luechtdiode** [comment]
Hier das Beispiel in der Netzwerk-Dashboard Ansicht, welche auch die Online-Erfassung steuert:
![grafik](https://github.com/luechtdiode/KuTu/assets/2457748/6a9f0e5f-4c43-4d6d-be9b-aac0b2603776)

Geräte Reihenfolge in der Online Erfassungs App für die Turner
![grafik](https://github.com/luechtdiode/KuTu/assets/2457748/ad8e9bfd-8edc-4dbd-bc21-e5d20d8518dd)

Geräte Reihenfolge in der Online Erfassungs App für die Turnerinnen
![grafik](https://github.com/luechtdiode/KuTu/assets/2457748/67c7a423-9dce-48c4-8b7a-7311f0e73812)

**Comment by luechtdiode** [comment]
Es wäre theortisch möglich, mit gemischtem Durchgang (nicht durchmischte Geräteriegen) die Reihenfolge der aufeinander folgenden Geräte wechle nur von Turnerinnen resp. Turner beturnt werden dürfen, in die gleiche Stationsnummer zu legen.

Das würde dann so aussehen:
|  Station | 1       |    2|       3|       4|
|--|--|--|--|--|
| Boden   |  x (m/w) | | ||
| Barren   |  |  x (m) | ||
| Balken   |  |  x (w) | ||
| Minitramp | | | x (m/w) ||
| Sprung      | | | | x (m/w) |

Einfach wird das allerdings nicht zum umsetzen ...

**Comment by david171290** [comment]
Danke für den Hinweis bzgl. getrennter Durchgänge, die dann zusammengefasst werden können.

Ich werde das Ganze nochmals durchdenken und melde mich anschließend wieder...
kann aber ein paar Tage dauern.

**Comment by luechtdiode** [comment]
Wie auch immer, ich habe eine Anpassung gemacht wie beschrieben. Nun ist es sogar möglich, gemischte Riegen zu definieren. Allerdings stimmen die berechneten Durchgangszeiten nicht, weil die aktuelle Logik davon ausgeht, dass die Geräterigen auf dem Startgerät jeweils bei allen Geräten zusammen bleiben. Wenn nun also auf Balken und Barren eine Riege startet, werden diese beiden Riegen beim Minitrampolin zusammengefasst und ergeben dort eine doppelt so grosse Gruppe, was einen Einfluss auf die Durchgangszeit haben müsste.

Hier zum ausprobieren: https://github.com/luechtdiode/KuTu/releases/tag/v2r3b3-beta1

**Comment by david171290** [comment]
Die Riegenblätter und deren Reihenfolge sieht jetzt genau so aus, wie es fürs Turn10 benötigt wird.
DANKE

Den Test der Reihenfolge über die mobile App, werde ich so schnell wie möglich noch nachholen und mich nochmals melden.
Sieht aber sehr vielversprechend aus.
