### ISSUE TITLE
Rangliste Falsche Reihenfolge

### ISSUE THREAD

**Issue by onzina** [luechtdiode/KuTu#79]
![Bildschirmfoto 2019-11-23 um 13 53 32](https://user-images.githubusercontent.com/58110290/69479159-93bf6300-0dfa-11ea-9ec9-830bface5b11.png)
Hallo, erstmal vielen Dank für die tolle App. Ich nutze sie für unsere Vereinsmeisterschaften.

Jedoch ist beim Erstellen der Rangliste manchmal ein Fehler drin. der 3. platz ist z.B. auf dem Screenshot eigentlich der 1. Woran kann das liegen?

Vielen Dank für die Antwort.
Elisabeth Hehle (Onzina)

**Comment by luechtdiode** [comment]
Hallo Elisabeth

Danke für die Meldung.
Vorerst habe ich mit den selben Werten eine korrekte Reihenfolge.
[Siehe Test-Rangliste](https://test-kutuapp.sharevic.net/api/scores/34cffff8-19df-4d7f-85ae-ade9d9e558af/8e8880ce-d088-450d-a7ff-48266633b36d/?html)

Kannst du mir beschreiben, in welchen Momenten die Reihenfolge falsch kommt?
z.B.

1.  Nach der Erfassung aller Resultate auf Rangliste gewechselt.
2.  Erst nach einer Korrektur einer Wertung (in der E- und/oder D-Note)
3.  Erst nach dem wieder öffnen des Wettkampfes
4.  Erst nach dem Neustart der App
5.  Nur im Netzwerk-Modus
6.  ...

Falls du einen Export des Wettkampfes hier anhängen könntest, könnte ich mit dem konkreten Fall von dir nach dem Fehler suchen.

**Comment by luechtdiode** [comment]
Fehler ist wieder aufgetaucht - nun aber reproduzierbar:
Passiert bei der Punktegleichstands-Regel für KuTu Wettkämpfe. Wenn leere Resultate erfasst sind, kommt die Logik durcheindander.

**Comment by luechtdiode** [comment]
Ist nun wie folgt implementiert:
Bei Punktegleichstand gewinnt höhere Summe der E-Noten, dann die höhere Summe der D-Noten, und dann Jugend vor Alter.
